### ISSUE TITLE
Create builtin type module

### ISSUE THREAD

**Issue by anandology** [brownplt/lambda-py#1]
We need to implement built-in type `module` to construct module objects. 

Following the conversion in the current implementation, it should go to `base/builtins/module.rkt`.

**Comment by akov** [comment]
Consider refactoring [CModule](https://github.com/brownplt/lambda-py/blob/master/base/python-core-syntax.rkt#L45)  to avoid name confusion or to merge its functionality into actual modules. (Or it may be unnecessary if a new scope system is being implemented) A CModule is how we handle hoisting of global names. A python program is desugared to a CModule which has a body (which is the actual code) and a prelude which is a series of assignments of global names to dummies so they're in the environment before the body is interp'd. Interpreting a CModule is just a matter of interpreting the prelude and then the body.
