### ISSUE TITLE
Bug: behavior of __xxx__ methods

### ISSUE THREAD

**Issue by anandology** [brownplt/lambda-py#12]
```
x[i]
```

is equivalent to:

```
x.__class__.__getitem__(x, i)
```

not:

```
x.__getitem__(i)
```

Same thing applies to all `__xxx__` methods.

See the testcase at [tests/bugs/dunder-methods.py](/brownplt/lambda-py/blob/master/tests/bugs/dunder-methods.py).

**Comment by amtriathlon** [comment]
Fixed in multiple_inheritance branch https://github.com/brownplt/lambda-py/commit/fa69d52067f32797720a22da37da4b25d8616be2
