### ISSUE TITLE
Bug: bound and unbound methods

### ISSUE THREAD

**Issue by anandology** [brownplt/lambda-py#13]
Consider the following code:

```
class Foo:
    def method(self, x):
        return x

foo = Foo()
```

`Foo.method` should be an unbound method that takes two arguments and `foo.method` should be a bound method that takes one argument.

The current implementation is not working like this.

See the testcase at [tests/bugs/methods.py](/brownplt/lambda-py/blob/master/tests/bugs/methods.py).

**Comment by amtriathlon** [comment]
Fixed in multiple_inheritance branch https://github.com/brownplt/lambda-py/commit/fa69d52067f32797720a22da37da4b25d8616be2
