### ISSUE TITLE
Field assignment when object is not an identifier

### ISSUE THREAD

**Issue by yz83** [brownplt/lambda-py#14]
The current implementation (in base/) does not handle field assignment when object is not an identifier and the field was not existed before the assignment. It is because the interpreter directly uses `(CId-x o)` (base/python-interp.rkt:779) in this case.

Test is in tests/bugs/test-assign-field.py.

**Comment by amtriathlon** [comment]
Test is passing and was moved to tests/python-reference/scope/test-assign-field.py
