### ISSUE TITLE
Bug: First operand of a binary operation is getting evaluated twice

### ISSUE THREAD

**Issue by anandology** [brownplt/lambda-py#17]
First operand of a binary operation is getting evaluated twice because of the way it desugared.

For example `f() + 0` is desugared to:

```
  (CApp
    (CGetField
      (CApp (CId 'f (GlobalId)) () (none))
      '__add__)
    ((CApp (CId 'f (GlobalId)) () (none))
     (CObject 'int (some (MetaNum 0))))
    (none))
```

Notice that f is applied twice here. It should have be desugared to something like this instead:

```
(CLet 'left-op (CApp (CId 'f (GlobalId)) () (none))
    (CApp
        (CGetField (CId 'left-op (LocalId)) '__add__)
        (CId 'left-op (LocalId))
        (CObject 'int (some (MetaNum 0)))))
```

**Comment by anandology** [comment]
Test case is available at [tests/bugs/test-add-with-funcs.py](/brownplt/lambda-py/blob/master/tests/bugs/test-add-with-funcs.py).

**Comment by shriram** [comment]
Ha: the oldest common bug in the world in program generators. It's worth
sanity-checking all of desugaring for this, since these create incredibly
subtle and annoying bugs.

(Related problem: make sure the natural fix for this doesn't create name
captures. Hygiene!)

Shriram

**Comment by akov** [comment]
There's a function [new-id](https://github.com/brownplt/lambda-py/blob/master/base/util.rkt#L199) in util.rkt that produces a unique symbol which is not legal in user-python because it starts with a number.

**Comment by amtriathlon** [comment]
Test was passing, so it was moved to https://github.com/brownplt/lambda-py/blob/master/tests/python-reference/types/test-add-with-funcs.py

**Comment by jpolitz** [comment]
Great, thanks.

Anyone know what fixed it...?

On Mon, Feb 4, 2013 at 6:20 PM, Alejandro Martinez <notifications@github.com

**Comment by amtriathlon** [comment]
To implement the correct behavior of bound/unbound methods I had to change
completely PyApp desugar, and now it is very simple:

[PyApp (fun args)
             (local [(define f (rec-desugar fun global? env (none)))
                     (define f-expr (DResult-expr f))
                     (define-values (results last-env)
                       (map-desugar args global? (DResult-env f) (none)))](DResult
                %28CApp f-expr results %28none%29%29
                last-env))]

so this bug is gone, but only today -while testing decorators- I found this
test passing and the issue was still open.

2013/2/4 Joe Politz notifications@github.com

> Great, thanks.
> 
> Anyone know what fixed it...?
> 
> On Mon, Feb 4, 2013 at 6:20 PM, Alejandro Martinez <
> notifications@github.com
> 
> > wrote:
> > 
> > Test was passing, so it was moved to
> > 
> > https://github.com/brownplt/lambda-py/blob/master/tests/python-reference/types/test-add-with-funcs.py
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/brownplt/lambda-py/issues/17#issuecomment-13105747>.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/brownplt/lambda-py/issues/17#issuecomment-13105843.

## 

Alejandro.

**Comment by jpolitz** [comment]
Awesome, thanks for noticing.

On Mon, Feb 4, 2013 at 6:40 PM, Alejandro Martinez <notifications@github.com
