### ISSUE TITLE
Bug: super assumes that self is called "self"

### ISSUE THREAD

**Issue by akov** [brownplt/lambda-py#20]
[Desugaring of super](https://github.com/brownplt/lambda-py/blob/master/base/python-desugar.rkt#L733) is special cased to take an argument of `(CId 'self (LocalId))` but python doesn't require it to have that name so somehow this desugaring process needs to keep track of the name of the first arg of the method somehow or the core implementation of super needs to be made smarter in this regard.

**Comment by amtriathlon** [comment]
This and #27 are solved in multiple_inheritance branch (https://github.com/brownplt/lambda-py/commit/8b9d151d945b39ac155016eefe545e9399a3ec1e)
