### ISSUE TITLE
function execution error

### ISSUE THREAD

**Issue by lijunsong** [brownplt/lambda-py#21]
```
def f(x,y):
    print(x,y)
f(1,2)
TypeError: Arity mismatch: expected '(), received (list (VObject 'int (some (MetaNum 2)) '#hash()))
```

And about the default arguments

```
def f(x,y=None):
    return (x,y)
print(f(1))
NameError: name 'x' is not defined
```

**Comment by sumnerwarren** [comment]
I think the first one is an error with the lib print function: I believe it currently only accepts one argument, not a vararg. That can easily be fixed. Not sure about the default arg. @akov might be know something about that. I imagine the way it's desugaring is losing the x for some reason.

**Comment by anandology** [comment]
I think default arguments are not implemented. It is a missing feature.

**Comment by sumnerwarren** [comment]
There is a half implementation which only works for one default argument right now. I have a feeling it's seeing the default arg and assuming it's the first argument and losing '''x''' in the process. But you're right, it's still a largely missing feature.

**Comment by sumnerwarren** [comment]
See #18.

**Comment by akov** [comment]
Turns out that the current sketchy default argument implementation doesn't cooperate when there are other arguments. It only works if there is exactly one argument and it has a default value. Looking into how to fix this.
