### ISSUE TITLE
Bug: object function variable will pass self in to the function

### ISSUE THREAD

**Issue by hichuang** [brownplt/lambda-py#23]
I'm writing generator class, and found an issue of the object member variable
suppose we have a class define as follow:

``` python
class A:
    def __init__(self, f):
        self.f = f
    def __next__(self):
        return self.f()
```

When I initialize an instance a say 

``` python
def func():
    print('test')

a = A(func)
a.__next__()
```

we will have an Arity Mismatch Error, because our implementation when calling self.f() will pass self to f() as well, which func did not take any argument

**Comment by amtriathlon** [comment]
I am having a similar problem with multiple inheritance tests, when a method is called as cls.method(obj) instead of obj.method() it gives arity mismatch, for example:

print("xxx".**str**())

works, but

str.**str**("xxx")

gives arity mismatch.

**Comment by mpmilano** [comment]
Yes - I noticed the same earlier. Not sure who to talk to about this.

**Comment by amtriathlon** [comment]
The problem, in both cases, is the lack of a method object, which should be constructed on attribute retrieval to distinguish bound/unbound calls (https://github.com/brownplt/lambda-py/issues/13), I planned to add this after multiple inheritance extensions, but according to an email of Matthew Milano on googlegroups the scope group is working on lookup order, so I think we should wait to have the new scope merged before.

**Comment by mpmilano** [comment]
Shoot - clarification. We aren't actually working on lookup order, we are
just assuming that that is roughly how look up order should work.

**Comment by amtriathlon** [comment]
Fixed in multiple_inheritance branch https://github.com/brownplt/lambda-py/commit/fa69d52067f32797720a22da37da4b25d8616be2
