### ISSUE TITLE
Bug: a.f() is desugared incorrectly

### ISSUE THREAD

**Issue by anandology** [brownplt/lambda-py#26]
This is related to issue #13. (see [testcase](/brownplt/lambda-py/blob/master/tests/bugs/methods.py#L18)).

`a.f()` is desugared as:

```
(CApp
    (CGetField (CId 'a (GlobalId)) 'f)
    (list (CId 'a (GlobalId)))
(none)))
```

This is implemented to support object methods. But it is not the appropriate place. This can be wrong in some cases. For example:

```
a.f = lambda x: x
a.f(4)
```

Ideally, it should be desugared to:

```
(CApp
    (CGetField (CId 'a (GlobalId)) 'f)
    (list)
    (none))
```

And object methods support should be handled by `CGetField` implementation.

**Comment by amtriathlon** [comment]
Hi Anand, this is essentially the problem with #13, I have planned to work on this after I finish with super(), but if you are ready to start now, go ahead!

**Comment by amtriathlon** [comment]
I will start looking at this problem since it its blocking me with super(), basically the super() object cannot be implemented without a correct implementation of method calls.

**Comment by amtriathlon** [comment]
Fixed in multiple_inheritance branch https://github.com/brownplt/lambda-py/commit/fa69d52067f32797720a22da37da4b25d8616be2
