### ISSUE TITLE
locals identifier gives NameError

### ISSUE THREAD

**Issue by amtriathlon** [brownplt/lambda-py#27]
locals() desugaring is done at application time, so:

mylocals = locals
print(mylocals())

gives NameError exception, super() has a similar problem.

**Comment by anandology** [comment]
I've implemented built-in function `globals` in [my fork](https://github.com/anandology/lambda-py/tree/modules). I can take care of implementing `locals`, if no one else is working on it.

**Comment by amtriathlon** [comment]
Hi Anand, I've implemented this in multiple_inheritance branch since I need the activation record's stack to access self and **class** (https://github.com/brownplt/lambda-py/commit/8b9d151d945b39ac155016eefe545e9399a3ec1e), but it depends on the new (static) scope.
