### ISSUE TITLE
"continue" isn't supported

### ISSUE THREAD

**Issue by dbp** [brownplt/lambda-py#29]
The current implementation does not support "continue". It is not parsed in get-structured-python.rkt, it does not exist in the surface language, etc. This may be non-trivial to add, I'm not sure (people more familiar with the implementation would have a better idea).

Here is a test case:

```
n = 0
while n < 10:
    n += 1
    if n % 2 == 0:
        continue
    print(n)
```

Which should print 1,3,5,7,9, but on our implementation it prints all the numbers. I'm still not sure why the parser isn't blowing up (continue is a 'nodetype "Continue" I think, and that isn't handled).

**Comment by sumnerwarren** [comment]
The parser is defaulting to a pass essentially. The new version of scope
will have continue added.

**Comment by sumnerwarren** [comment]
Continue is supported as of 44a523ce7b
