### ISSUE TITLE
Combined assignment on __getitem__ lookup doesn't work

### ISSUE THREAD

**Issue by jpolitz** [brownplt/lambda-py#40]
This program:

```
a = [1,2]
a[0] += 1
___assertEqual(a[0], 2)
```

Should pass, but gives a syntax error on the second line:

desugar: bad syntax: LexSubscript has context 'Store' outside a LexAssign

Test in test-dict-aug-assign.py.

**Comment by mpmilano** [comment]
Desugar appears to be handling augAssign incorrectly in general.  I've fixed this specific bug in the scope-rewrite branch (46090866cbfc9037b599f9c89d4a850305884ebe), but more work remains to be done to make desugar sensible.
