### ISSUE TITLE
Let binding swallowing errors

### ISSUE THREAD

**Issue by dbp** [brownplt/lambda-py#46]
interp-let in python-interp.py is not handling the various result types. This means that if you ever have an exception thrown in the value of a let binding, it will be swallowed. 

One simple example comes from noticing that the desugaring for slices uses CLet (but this should apply _anywhere_ that desugars to a CLet):

```
def ex():
    raise Exception("Hello")
ex()[0:1]
```

Python, when run, reports the exception:

```
Traceback (most recent call last):
  File "../tests/bugs/let.py", line 3, in <module>
    ex()[0:1]
  File "../tests/bugs/let.py", line 2, in ex
    raise Exception("Hello")
Exception: Hello
```

But LambdaPy reports, incorrectly, that the issue is that Exception doesn't have slice:

```
AttributeError: object Exception has no attribute __slice__
```

**Comment by amtriathlon** [comment]
Now interp is handling exceptions in CLet case and this example works as expected.
