### ISSUE TITLE
Implement __import__ for simple modules

### ISSUE THREAD

**Issue by anandology** [brownplt/lambda-py#5]
Implement `__import __` to work with simple modules (no nesting).

This should import modules from `python-lib/`.

**Comment by lijunsong** [comment]
some resources:
- http://www.python.org/dev/peps/pep-0302/#specification-part-1-the-importer-protocol
- [import statement from language reference](http://docs.python.org/3.2/reference/simple_stmts.html#the-import-statement)
- [bootstrap importlib](http://sayspy.blogspot.com/2012/02/how-i-bootstrapped-importlib.html)
- python source file /Lib/importlib/_bootstrap.py. _bootsrap.py needs injection of several modules, including sys and imp, etc.
