### ISSUE TITLE
vpointer not being dereferenced in all cases

### ISSUE THREAD

**Issue by mpmilano** [brownplt/lambda-py#51]
class c:
 x = iter  
c().x()

yields 
TypeError: Pointer to address 5854.

I'm trying to track down a few issues related to method binding in classes, having pointer dereference here seems important.

**Comment by jpolitz** [comment]
I'm checking up on this.

I don't think it's a failure to dereference.  Just seeing a pointer isn't a
bad thing anymore: all objects are in pointers.  It might just be a bad
error message.

**Comment by jpolitz** [comment]
Closed by 6596253fa5f4d7a2bda27616fa86fb5fa756dd45 making the error message clearer in this case.
