### ISSUE TITLE
constructing lists from dict does not follow spec

### ISSUE THREAD

**Issue by mpmilano** [brownplt/lambda-py#52]
Right now, constructing a list from a dictionary will get you a list of key,value pairs.  It should only get you a list of keys.  

This is the only remaining bug preventing the test locals-class.py from working.

**Comment by jpolitz** [comment]
This should just be a one-line change in dict.py --- change pair[1] to
pair[1][0].

I'm off in writing land and don't want to deal w/regression testing right
now, but this should be trivial to do.

**Comment by amtriathlon** [comment]
I've fixed the dict.**list** issue but, the locals-class.py test now is failing due to interactions with the new attribute lookup regime: locals() is reporting local variables of functions used in class and method initialization.

**Comment by mpmilano** [comment]
Locals is broken right now due to the merge.  I'm trying to figure out what
happened to it.

~matthew
