### ISSUE TITLE
class type has no attribute __dict__

### ISSUE THREAD

**Issue by mpmilano** [brownplt/lambda-py#53]
Classes should have a **dict**, but they don't in rython.  This is the only thing preventing the test nonlocal-class.py from working.

**Comment by amtriathlon** [comment]
With the new attribute regime a snapshot **dict** attribute would be easy
to add having an obj-dict primitive (or CDir expression, the same which is
needed to implement dir(obj)),.
A dynamic **dict** reflecting updates in both ways would be far more
complicated but, a nice feature to have.

2013/3/24 Matthew Milano notifications@github.com

> Classes should have a _dict_, but they don't in rython. This is the only
> thing preventing the test nonlocal-class.py from working.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/brownplt/lambda-py/issues/53
> .

## 

Alejandro.

**Comment by jpolitz** [comment]
**dict** should return a dictionary with a special setitem that performs
attribute update... would that work?

**Comment by amtriathlon** [comment]
Yes, this would solve the way **dict**["a"] = x -> obj.a = x, for the other
direction that dictionary should have also a special getitem that performs
attribute lookup on the object.

2013/3/24 Joe Politz notifications@github.com

> **dict** should return a dictionary with a special setitem that performs
> attribute update... would that work?
> 
> On Sun, Mar 24, 2013 at 12:24 PM, Alejandro Martinez <
> notifications@github.com> wrote:
> 
> > With the new attribute regime a snapshot **dict** attribute would be
> > easy
> > to add having an obj-dict primitive (or CDir expression, the same which
> > is
> > needed to implement dir(obj)),.
> > A dynamic **dict** reflecting updates in both ways would be far more
> > complicated but, a nice feature to have.
> > 
> > 2013/3/24 Matthew Milano notifications@github.com
> > 
> > > Classes should have a _dict_, but they don't in rython. This is the
> > > only
> > > thing preventing the test nonlocal-class.py from working.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/brownplt/lambda-py/issues/53>
> > > .
> > 
> > ## 
> > 
> > Alejandro.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/brownplt/lambda-py/issues/53#issuecomment-15361905>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/brownplt/lambda-py/issues/53#issuecomment-15362007
> .

## 

Alejandro.

**Comment by amtriathlon** [comment]
I think a dict whose **internaldict** is a computed attribute (from the
oject internal dict) and setitem perfoms attribute update could be a nice
solution.

2013/3/24 Alejandro Martinez amtriathlon@gmail.com

> Yes, this would solve the way **dict**["a"] = x -> obj.a = x, for the
> other direction that dictionary should have also a special getitem that
> performs attribute lookup on the object.
> 
> 2013/3/24 Joe Politz notifications@github.com
> 
> > **dict** should return a dictionary with a special setitem that performs
> > attribute update... would that work?
> > 
> > On Sun, Mar 24, 2013 at 12:24 PM, Alejandro Martinez <
> > notifications@github.com> wrote:
> > 
> > > With the new attribute regime a snapshot **dict** attribute would be
> > > easy
> > > to add having an obj-dict primitive (or CDir expression, the same which
> > > is
> > > needed to implement dir(obj)),.
> > > A dynamic **dict** reflecting updates in both ways would be far more
> > > complicated but, a nice feature to have.
> > > 
> > > 2013/3/24 Matthew Milano notifications@github.com
> > > 
> > > > Classes should have a _dict_, but they don't in rython. This is the
> > > > only
> > > > thing preventing the test nonlocal-class.py from working.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub<
> > > > https://github.com/brownplt/lambda-py/issues/53>
> > > > .
> > > 
> > > ## 
> > > 
> > > Alejandro.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/brownplt/lambda-py/issues/53#issuecomment-15361905>
> > > .
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/brownplt/lambda-py/issues/53#issuecomment-15362007
> > .
> 
> ## 
> 
> Alejandro.

## 

Alejandro.

**Comment by amtriathlon** [comment]
The update part is necessary only for instances, for classes the **dict**
is read only, so the proposed solution would be:

1) **dict** is a computed attributed returning a subclass of dict bound to
the class object
2) that subclass of dict has overrides attribute **internaldict** with a
computed one using obj-dir primitive operation or CDir expression.
3) that subclass of dict overrides **setitem** to update the object
internal dict only when the object is not a class, this requires CSetAttr
and could be left for the future.

Is Anyone willing to tackle the obj-dir/CDir part?

**Comment by amtriathlon** [comment]
I've implemented the snapshot version, it works for instances and class objects, and added a simple regression test, I think it is too late to start with the dynamic version, at least for me.

**Comment by jpolitz** [comment]
It's fine to stop there for now.  Thanks!

**Comment by jpolitz** [comment]
I'd say, if you want to do anything still, go hunt down some tests that we
can pass now and move them over.  I'd even prefer this to you figuring out
my bug in the other thread :-)

**Comment by amtriathlon** [comment]
I just come back to home, regression test have finished ok so I pushed the
commit but, I couldn't look at the bug yet, sorry! It is in my pending
list, together with **dir** which is within reach now, and looking for some
more tests...

2013/3/25 Joe Politz notifications@github.com

> I'd say, if you want to do anything still, go hunt down some tests that we
> can pass now and move them over. I'd even prefer this to you figuring out
> my bug in the other thread :-)
> 
> On Mon, Mar 25, 2013 at 7:18 PM, Joe Gibbs Politz joe@cs.brown.edu
> wrote:
> 
> > It's fine to stop there for now. Thanks!
> > 
> > On Mon, Mar 25, 2013 at 7:16 PM, Alejandro Martinez <
> > notifications@github.com> wrote:
> > 
> > > I've implemented the snapshot version, it works for instances and class
> > > objects, and added a simple regression test, I think it is too late to
> > > start with the dynamic version, at least for me.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/brownplt/lambda-py/issues/53#issuecomment-15431749>
> > > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/brownplt/lambda-py/issues/53#issuecomment-15431856
> .

## 

Alejandro.

**Comment by amtriathlon** [comment]
The dynamic version was easier than I expected: the **dict** attribute is an object of dict_proxy class, which is a subclass of dict overriding six dict methods, I will push an update.
