### ISSUE TITLE
string identity fails for equal strings

### ISSUE THREAD

**Issue by amtriathlon** [brownplt/lambda-py#57]
For example:

s = "abc"
assert s is "abc"

works in Python and fails in lambda-py, that's the reason these control tests https://github.com/brownplt/lambda-py/commit/95dad02d1cc4255dbfda3f8e7008cfc794062084 are failing, I moved them to tests/bugs.

**Comment by amtriathlon** [comment]
It is not a bug, identity is not the same as equality for str even in CPython 3.2.3:

```
Python 3.2.3 (default, Apr 11 2012, 07:15:24) [MSC v.1500 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> a = 'pub'
>> b = ''.join(['p', 'u', 'b'])
>>> a == b
True
>>> a is b
False
>>> 
```

Example from http://stackoverflow.com/questions/1504717/python-vs-is-comparing-strings-is-fails-sometimes-why

**Comment by jpolitz** [comment]
Sorry I meant that it was a broken feature to use to test.  My message was
just vague.
