### ISSUE TITLE
Comprehensions "leak" the target list in the enclosing scope

### ISSUE THREAD

**Issue by amtriathlon** [brownplt/lambda-py#62]
For example:

```
[x for x in (1, 2)]; print(x)
```

prints 2 instead to raise NameError as CPython does.

According to http://docs.python.org/3.2/reference/expressions.html#grammar-token-comprehension this shouldn't happen:

> Note that the comprehension is executed in a separate scope,
> so names assigned to in the target list don’t “leak” in the enclosing scope.

**Comment by sumnerwarren** [comment]
I'm not sure how we currently desugar comprehensions, but couldn't this just be solved by adding

`del x`

right after it? Instead of dealing with creating a new scope?

**Comment by amtriathlon** [comment]
It is not that easy, the bindings for the targets must be restored to their values in the enclosing scope when they are present, and this must be done even if the comprehension raises an exception, look this simple test: https://github.com/brownplt/lambda-py/commit/34b635f2ad8a3404d6313889004a6ff136c69902
Even when it can be done, I think a separate scope is a more natural way to deal with this.

**Comment by jpolitz** [comment]
I think phase1 or phase2 just needs to look for LexListComp (and
LexComprehen?) and add a new LexBlock around it; that should suffice for
getting the rest of scope desugaring to notice it as a separate block and
handle things correctly.

Matthew, does that sound about right?  Should it happen before or after
phase1?

**Comment by sumnerwarren** [comment]
With that example we could simply replace all occurrences of `x` with a new
unique identifier and then del that afterward. That would avoid shadowing
issues. I'm not opposed to handling this with proper scope, but I thought
that was relatively involved and this seems like a sufficient/easier fix.

**Comment by mpmilano** [comment]
It's far easier just to have phase1 care about this. Not worth the hacky
delete or rename suggestions.

**Comment by amtriathlon** [comment]
Following Matthew's suggestion I did the following changes to phase 1: 
1) added a LexBlock without variables around LexListComp and LexGeneratorExp in pre-desugar.
2) included LexComprehen as a case in extract-locals-helper, find-all-instance, replace-all-instance and bind-locals, with a logic similar to LexFor, to take care of target variables.
This test and the regression ones in iter and scope are passing so I will push a commit to master for review.

**Comment by mpmilano** [comment]
That's exactly how I would have done it. Thanks Alejandro!
