### ISSUE TITLE
Not catching some scope syntax errors

### ISSUE THREAD

**Issue by jpolitz** [brownplt/lambda-py#67]
This program is a Python syntax error:

```
x = 100
def f():
    nonlocal x
    x += 1

f()
```

Neither our parser nor our scope desugaring says so, though.

**Comment by mpmilano** [comment]
This is a result of switching from python's parser to our native racket parser.

We used to catch syntax errors by just calling python's compile() function.

In earlier iterations of the project we had a catch-syntax-errors phase, but this was retired when it was pointed out that we could just rely on actual python to do that for us.

I can re-enable that phase in the desugar pipeline, but it is both overzealous in the syntax errors it reports and does not report all syntax errors; it would require some real effort to ensure the phase actually checks all syntax errors correctly. Such is the fate of abandoned code.

So how would you like to proceed?

**Comment by jmillikan** [comment]
I'm available, just in case you want me to mess with the parser.

**Comment by mpmilano** [comment]
The parser probably isn't the right place to handle these syntax errors - most of them (this example included) require information that isn't available until during phase1.  At the moment, I'm not even sure how much code we'd be looking at anyway - what really needs to happen is for someone to categorize all the non-grammar-related syntax errors so that we have a good idea of the scope. (pun intended).

**Comment by jmillikan** [comment]
If it helps, the non-grammar syntax errors currently being _caught_ by the
native parser in python-parser.rkt are a fairly short list. Some of these
are exercised in the tests-bad-syntax folder.
- line 484: Starred expression in non-assignment
- line 612: Mixed unicode/bytestring literals
- line 618: Storing to True/False/None
- line 909: Un-parenthesized generator with other arguments
- line 976: Duplicate argument names
- line 986: In args, can't use a \* without a name and without named
  arguments.
- line 1068: validate-assign-target: Allow only valid assignment targets
  (except True, False, None, see above)

There are probably others, besides these and scope, but I'm not aware of
them.

**Comment by jpolitz** [comment]
Yeah, I don't think your parser could be expected to catch these, Jesse,
since there's some amount of binding-structure information needed to throw
these errors that simply isn't part of the parser.  IMO, the right thing to
do is to add them to the scope phase, and report them as "SyntaxError"s, or
desugar the whole program to "raise SyntaxError" when they are encountered.
 We should leave this issue open until we can do it right.

It's not the end of the world.  From a tool engineering perspective it just
means that lambda-py is best used when augmented with e.g. compile(),
because we give a semantics to some programs that Python deems to have
syntax errors.  We should close that gap as well as we can.

**Comment by mpmilano** [comment]
For those interested, you can see where we used to handle this on line 192 of python-phase1.rkt circa march 25th.  Here's a link to that file at the right point in history on github:

https://github.com/brownplt/lambda-py/blob/6f23be9938b3188f75daf5e38c6a0e3942175998/base/python-phase1.rkt

**Comment by mpmilano** [comment]
I've pushed a fix for the syntax errors I know about which depend on scope. If we find more, we'll open more issues.
